use_frameworks!
platform :ios, '10.0'

target 'Httper' do
    pod 'Alamofire'
    pod 'ESPullToRefresh', :git => 'https://github.com/eggswift/pull-to-refresh.git'
    pod 'Eureka'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'Kanna'
    pod 'Kingfisher'
    pod 'M80AttributedLabel'
    pod 'MGFormatter'
    pod 'MGKeyboardAccessory'
    pod 'MGSelector'
    pod 'NVActivityIndicatorView'
    pod 'PagingKit'
    pod 'R.swift'
    pod 'ReachabilitySwift'
    pod 'Reusable'
    pod 'RxAlamofire'
    pod 'RxAlertViewable'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'RxFlow'
    pod 'RxKeyboard'
    pod 'RxKingfisher'
    pod 'SnapKit'
    pod 'SwipeBack'
    pod 'SwiftyUserDefaults'
    pod 'SwiftyJSON'
    pod 'UIGradient', :git => 'https://github.com/lm2343635/UIGradient.git'
    pod 'UIImageView+Extension'
    pod 'UITextView+Placeholder'
end
